module.exports = {
  QUANTIZE_RECORDING: 'ROUTES/ROUTE/QUANTIZE_RECORDING',
  QUANTIZE_PLAYBACK: 'ROUTES/ROUTE/QUANTIZE_PLAYBACK',
  DOUBLE_RECORDING_QUANTIZATION: 'ROUTES/ROUTE/DOUBLE_RECORDING_QUANTIZATION',
  HALVE_RECORDING_QUANTIZATION: 'ROUTES/ROUTE/HALVE_RECORDING_QUANTIZATION',
}
;