module.exports = {
  START_RECORDING: 'RECORDING/START_RECORDING',
  STOP_RECORDING: 'RECORDING/STOP_RECORDING',
  SET_TIMELINE_LENGTH: 'RECORDING/SET_TIMELINE_LENGTH',
  ADD_TO_TIMELINE: 'RECORDING/ADD_TO_TIMELINE',
};
