module.exports = {
  NEXT_INDEX: 'MENUS/NEXT_INDEX',
  PREVIOUS_INDEX: 'MENUS/PREVIOUS_INDEX',
  SET_MENU_ITEMS: 'MENUS/SET_MENU_ITEMS',
  SAVE_MENU_AS_PREVIOUS: 'MENUS/SAVE_MENU_AS_PREVIOUS',
  SET_TITLE: 'MENUS/SET_TITLE',
  SET_INDEX: 'MENUS/SET_INDEX',
  UPDATE_MENU_ITEM: 'MENUS/UPDATE_MENU_ITEM',
};
