module.exports = {
  UPDATE: 'ROUTES/ROUTE/UPDATE',
  QUANTIZE_RECORDING: 'ROUTES/ROUTE/QUANTIZE_RECORDING',
  QUANTIZE_PLAYBACK: 'ROUTES/ROUTE/QUANTIZE_PLAYBACK',
  UPDATE_SEQUENCE: 'ROUTES/ROUTE/UPDATE_SEQUENCE',
}