module.exports = {
  CONTROL: 'BUTTONS/CONTROL',
  TRANSPORT: 'BUTTONS/TRANSPORT',
  RECORD: 'BUTTONS/RECORD',
  button: {
    DOWN: 'BUTTON/DOWN',
    PRESS_AND_HOLD: 'BUTTON/PRESS_AND_HOLD',
    UP: 'BUTTON/UP',
    PRESS_AND_HOLD_RELEASE: 'BUTTON/PRESS_AND_HOLD_RELEASE',
  },
};
