module.exports = {
  CONTROL: 'KNOBS/CONTROL',
  knob: {
    MOVE: 'KNOB/MOVE',
    RESET_MOVEMENT: 'KNOB/RESET_MOVEMENT',
    SET_INTERCEPTOR: 'KNOB/SET_INTERCEPTOR',
    CLEAR_INTERCEPTOR: 'KNOB/CLEAR_INTERCEPTOR',
  },
};
