module.exports = {
  INCREMENT_N: 'ROUTES/ROUTE/INCREMENT_N',
  INCREMENT_MULTIPLIER: 'ROUTES/ROUTE/INCREMENT_MULTIPLIER',
  DECREMENT_N: 'ROUTES/ROUTE/DECREMENT_N',
  DECREMENT_MULTIPLIER: 'ROUTES/ROUTE/DECREMENT_MULTIPLIER',
};
